// Weekly Moontuner SEO Digest — pulls Search Console data + sends email via Resend.
// Triggered by pg_cron every Monday 13:00 UTC. Also callable manually.
import { corsHeaders } from 'npm:@supabase/supabase-js@2/cors';

const GSC_GATEWAY = 'https://connector-gateway.lovable.dev/google_search_console';
const RESEND_GATEWAY = 'https://connector-gateway.lovable.dev/resend';
const SITE = 'https://moontuner.xyz/';

function isoDaysAgo(n: number) {
  const d = new Date(Date.now() - n * 86400000);
  return d.toISOString().slice(0, 10);
}

async function gscQuery(body: unknown, lovableKey: string, gscKey: string) {
  const url = `${GSC_GATEWAY}/webmasters/v3/sites/${encodeURIComponent(SITE)}/searchAnalytics/query`;
  const r = await fetch(url, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${lovableKey}`,
      'X-Connection-Api-Key': gscKey,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify(body),
  });
  const text = await r.text();
  if (!r.ok) throw new Error(`GSC ${r.status}: ${text}`);
  return JSON.parse(text);
}

function row(cells: (string | number)[]) {
  return `<tr>${cells.map((c) => `<td style="padding:6px 10px;border-bottom:1px solid #222;color:#e6e1d6">${c}</td>`).join('')}</tr>`;
}

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') return new Response('ok', { headers: corsHeaders });

  const LOVABLE_API_KEY = Deno.env.get('LOVABLE_API_KEY');
  const GSC_KEY = Deno.env.get('GOOGLE_SEARCH_CONSOLE_API_KEY');
  const RESEND_API_KEY = Deno.env.get('RESEND_API_KEY');

  // Recipient is config, not a secret. Override per-request via { recipient } in POST body if needed.
  let RECIPIENT = 'hello@moontuner.xyz';
  try {
    if (req.method === 'POST') {
      const body = await req.clone().json().catch(() => ({}));
      if (body?.recipient && typeof body.recipient === 'string') RECIPIENT = body.recipient.trim();
    }
  } catch { /* ignore */ }

  if (!LOVABLE_API_KEY || !GSC_KEY || !RESEND_API_KEY) {
    return new Response(
      JSON.stringify({ error: 'Missing one of LOVABLE_API_KEY, GOOGLE_SEARCH_CONSOLE_API_KEY, RESEND_API_KEY' }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } },
    );
  }

  const startDate = isoDaysAgo(10); // GSC has ~2-3 day lag
  const endDate = isoDaysAgo(3);

  let totals = { clicks: 0, impressions: 0, ctr: 0, position: 0 };
  let topQueries: any[] = [];
  let topPages: any[] = [];
  let warning = '';

  try {
    const t = await gscQuery({ startDate, endDate, dimensions: [], rowLimit: 1 }, LOVABLE_API_KEY, GSC_KEY);
    if (t.rows?.[0]) totals = t.rows[0];
    const q = await gscQuery({ startDate, endDate, dimensions: ['query'], rowLimit: 10 }, LOVABLE_API_KEY, GSC_KEY);
    topQueries = q.rows || [];
    const p = await gscQuery({ startDate, endDate, dimensions: ['page'], rowLimit: 10 }, LOVABLE_API_KEY, GSC_KEY);
    topPages = p.rows || [];
  } catch (e) {
    warning = `<p style="color:#e85d3a">Search Console fetch failed: ${(e as Error).message}. The site may not be verified yet, or has no data for this window.</p>`;
  }

  const html = `
<!doctype html><html><body style="background:#0a0a0a;color:#e6e1d6;font-family:Inter,sans-serif;padding:32px;max-width:760px;margin:auto">
  <h1 style="font-family:Playfair Display,serif;font-weight:300;color:#fffbe6;font-size:28px;margin:0 0 8px">Moontuner SEO Weekly Digest</h1>
  <p style="color:#8a8a8a;font-size:13px;margin:0 0 24px">${startDate} → ${endDate} · moontuner.xyz</p>
  ${warning}
  <h2 style="font-weight:300;color:#4ECDC4;font-size:16px;text-transform:uppercase;letter-spacing:.2em;margin-top:32px">Totals</h2>
  <table style="width:100%;border-collapse:collapse;margin-top:8px;font-size:14px">
    ${row(['Clicks', totals.clicks ?? 0])}
    ${row(['Impressions', totals.impressions ?? 0])}
    ${row(['CTR', `${((totals.ctr ?? 0) * 100).toFixed(2)}%`])}
    ${row(['Avg position', (totals.position ?? 0).toFixed(1)])}
  </table>
  <h2 style="font-weight:300;color:#4ECDC4;font-size:16px;text-transform:uppercase;letter-spacing:.2em;margin-top:32px">Top Queries</h2>
  <table style="width:100%;border-collapse:collapse;font-size:14px">
    ${row(['Query', 'Clicks', 'Impr', 'CTR', 'Pos'])}
    ${topQueries.map((r) => row([r.keys[0], r.clicks, r.impressions, `${(r.ctr * 100).toFixed(1)}%`, r.position.toFixed(1)])).join('') || row(['No data', '', '', '', ''])}
  </table>
  <h2 style="font-weight:300;color:#4ECDC4;font-size:16px;text-transform:uppercase;letter-spacing:.2em;margin-top:32px">Top Pages</h2>
  <table style="width:100%;border-collapse:collapse;font-size:14px">
    ${row(['Page', 'Clicks', 'Impr', 'CTR', 'Pos'])}
    ${topPages.map((r) => row([r.keys[0].replace('https://moontuner.xyz', ''), r.clicks, r.impressions, `${(r.ctr * 100).toFixed(1)}%`, r.position.toFixed(1)])).join('') || row(['No data', '', '', '', ''])}
  </table>
  <p style="color:#666;font-size:12px;margin-top:40px">Auto-generated by Moontuner. Replies are not monitored.</p>
</body></html>`;

  const r = await fetch('https://api.resend.com/emails', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${RESEND_API_KEY}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      from: 'Moontuner SEO <onboarding@resend.dev>',
      to: [RECIPIENT],
      subject: `Moontuner SEO Digest · ${startDate} → ${endDate}`,
      html,
    }),
  });
  const sendBody = await r.text();
  return new Response(JSON.stringify({ ok: r.ok, totals, send: sendBody }), {
    status: r.ok ? 200 : 500,
    headers: { ...corsHeaders, 'Content-Type': 'application/json' },
  });
});
