/**
 * create-gift-checkout
 *
 * Creates a Stripe Checkout session for gifting a membership or report.
 * On success, a `gifts` row is created with a unique claim_code that the
 * recipient can use to activate their gift.
 *
 * Body: {
 *   giftType: 'membership_1month' | 'membership_3month' | 'membership_6month' | 'report' | 'digital_good',
 *   tier?: 'reflective' | 'insight' | 'practitioner',  // for membership gifts
 *   productId?: string,                                  // for report/digital_good gifts
 *   recipientEmail: string,
 *   message?: string,
 *   senderUserId?: string,
 * }
 */
import { serve } from "https://deno.land/std@0.190.0/http/server.ts";
import Stripe from "https://esm.sh/stripe@18.5.0";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
};

type GiftType =
  | "membership_1month"
  | "membership_3month"
  | "membership_6month"
  | "report"
  | "digital_good";

const GIFT_CATALOG: Record<
  GiftType,
  { label: string; amountCents: number }
> = {
  membership_1month: { label: "1-Month Reflective Membership Gift", amountCents: 1200 },
  membership_3month: { label: "3-Month Reflective Membership Gift", amountCents: 3000 },
  membership_6month: { label: "6-Month Reflective Membership Gift", amountCents: 5400 },
  report: { label: "Report Gift", amountCents: 1700 },
  digital_good: { label: "Digital Good Gift", amountCents: 1500 },
};

serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });

  try {
    const stripe = new Stripe(Deno.env.get("STRIPE_SECRET_KEY") ?? "", {
      apiVersion: "2025-08-27.basil",
    });
    const supabase = createClient(
      Deno.env.get("SUPABASE_URL") ?? "",
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "",
    );

    const body = await req.json();
    const {
      giftType,
      tier,
      productId,
      recipientEmail,
      message,
      senderUserId,
    } = body as {
      giftType: GiftType;
      tier?: string;
      productId?: string;
      recipientEmail: string;
      message?: string;
      senderUserId?: string;
    };

    if (!giftType || !GIFT_CATALOG[giftType]) {
      return json({ error: "Invalid giftType" }, 400);
    }
    if (!recipientEmail) {
      return json({ error: "recipientEmail required" }, 400);
    }

    const catalog = GIFT_CATALOG[giftType];

    // If a custom product is involved, look up its price
    let amountCents = catalog.amountCents;
    let productLabel = catalog.label;
    if ((giftType === "report" || giftType === "digital_good") && productId) {
      const { data: product } = await supabase
        .from("digital_products")
        .select("label, amount_cents")
        .eq("id", productId)
        .single();
      if (product) {
        amountCents = product.amount_cents;
        productLabel = `${product.label} — Gift`;
      }
    }

    // Create pending gift row (claim_code auto-generated by DB default)
    const { data: gift, error: insertErr } = await supabase
      .from("gifts")
      .insert({
        sender_user_id: senderUserId ?? null,
        recipient_email: recipientEmail,
        gift_type: giftType,
        tier: tier ?? null,
        product_id: productId ?? null,
        message: message ?? null,
        status: "pending",
        expires_at: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000).toISOString(),
      })
      .select()
      .single();

    if (insertErr || !gift) throw insertErr ?? new Error("Gift insert failed");

    const origin = req.headers.get("origin") ?? "https://moontuner.xyz";

    const session = await stripe.checkout.sessions.create({
      mode: "payment",
      line_items: [
        {
          quantity: 1,
          price_data: {
            currency: "usd",
            unit_amount: amountCents,
            product_data: {
              name: productLabel,
              description: `A thoughtful gift for ${recipientEmail}`,
            },
          },
        },
      ],
      success_url: `${origin}/gift/confirmation?gift_id=${gift.id}&session_id={CHECKOUT_SESSION_ID}`,
      cancel_url: `${origin}/gift`,
      customer_email: senderUserId ? undefined : recipientEmail,
      metadata: {
        purchase_type: "gift",
        gift_id: gift.id,
        gift_type: giftType,
        recipient_email: recipientEmail,
      },
    });

    // Attach stripe session ID to gift
    await supabase
      .from("gifts")
      .update({ stripe_session_id: session.id })
      .eq("id", gift.id);

    return json({ url: session.url, giftId: gift.id });
  } catch (err) {
    console.error("create-gift-checkout error:", err);
    return json({ error: err instanceof Error ? err.message : String(err) }, 500);
  }
});

function json(data: unknown, status = 200) {
  return new Response(JSON.stringify(data), {
    status,
    headers: { ...corsHeaders, "Content-Type": "application/json" },
  });
}
