/**
 * AILabel
 *
 * A small, transparent label indicating that adjacent content was
 * generated by the AI synthesis engine. Supports the privacy
 * requirement that users understand what is being synthesized.
 */

interface AILabelProps {
  cached?: boolean;
  className?: string;
}

export function AILabel({ cached = false, className = '' }: AILabelProps) {
  return (
    <span
      className={`inline-flex items-center gap-1.5 text-[0.55rem] tracking-[0.2em] uppercase font-sans ${className}`}
      title="Generated by Moontuner's reflective synthesis engine based on your activity record."
      style={{ color: 'hsl(38 90% 58% / 0.45)' }}
    >
      <span
        className="inline-block w-1 h-1 rounded-full"
        style={{ background: 'hsl(38 90% 58% / 0.4)' }}
      />
      AI synthesis{cached ? ' · cached' : ''}
    </span>
  );
}
