// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/get-current-moon-phase.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import * as Astronomy from "npm:astronomy-engine@^2.1.19";
function phaseName(angle) {
  const a = (angle % 360 + 360) % 360;
  if (a < 22.5 || a >= 337.5) return "New Moon";
  if (a < 67.5) return "Waxing Crescent";
  if (a < 112.5) return "First Quarter";
  if (a < 157.5) return "Waxing Gibbous";
  if (a < 202.5) return "Full Moon";
  if (a < 247.5) return "Waning Gibbous";
  if (a < 292.5) return "Last Quarter";
  return "Waning Crescent";
}
var get_current_moon_phase_default = defineTool({
  name: "get_current_moon_phase",
  title: "Get current moon phase",
  description: "Return the current moon phase angle, phase name, illumination percentage, and Moon zodiac sign for right now (UTC).",
  inputSchema: {},
  annotations: {
    readOnlyHint: true,
    idempotentHint: false,
    openWorldHint: false
  },
  handler: () => {
    const now = /* @__PURE__ */ new Date();
    const angle = Astronomy.MoonPhase(now);
    const illum = Astronomy.Illumination(Astronomy.Body.Moon, now);
    const eq = Astronomy.Equator(Astronomy.Body.Moon, now, {
      latitude: 0,
      longitude: 0,
      height: 0
    }, true, true);
    const ecl = Astronomy.Ecliptic(eq.vec);
    const signs = [
      "Aries",
      "Taurus",
      "Gemini",
      "Cancer",
      "Leo",
      "Virgo",
      "Libra",
      "Scorpio",
      "Sagittarius",
      "Capricorn",
      "Aquarius",
      "Pisces"
    ];
    const signIdx = Math.floor((ecl.elon % 360 + 360) % 360 / 30);
    const payload = {
      timestampUtc: now.toISOString(),
      phaseAngleDegrees: Number(angle.toFixed(3)),
      phaseName: phaseName(angle),
      illuminationPercent: Number((illum.phase_fraction * 100).toFixed(2)),
      moonSign: signs[signIdx],
      moonEclipticLongitudeDegrees: Number(ecl.elon.toFixed(3))
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/get-my-profile.ts
import { createClient } from "npm:@supabase/supabase-js@^2.94.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var get_my_profile_default = defineTool2({
  name: "get_my_profile",
  title: "Get my Moontuner profile",
  description: "Return the signed-in user's Moontuner profile: display name, email, birth date/time/location, and preferences.",
  inputSchema: {},
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("profiles").select("email, full_name, display_name, birth_date, birth_time, birth_location, private_mode, data_visibility, created_at").eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? {}, null, 2) }],
      structuredContent: { profile: data ?? null }
    };
  }
});

// src/lib/mcp/tools/list-my-natal-reports.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.94.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser2(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_my_natal_reports_default = defineTool3({
  name: "list_my_natal_reports",
  title: "List my natal reports",
  description: "List the signed-in user's Moontuner natal reports (astro-harmonic charts). Returns id, name, birth details, sun/moon/ascendant, and any generated audio/PDF URLs.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("Maximum reports to return. Default 20.")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const email = ctx.getUserEmail();
    if (!email) {
      return { content: [{ type: "text", text: "No verified email on token" }], isError: true };
    }
    const { data, error } = await supabaseForUser2(ctx).from("natal_reports").select("id, name, email, birth_date, birth_time, birth_location, sun_sign, moon_sign, ascendant, audio_url, pdf_url, chart_image_url, created_at").eq("email", email).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { reports: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-my-purchases.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.94.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^4.4.3";
function supabaseForUser3(ctx) {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_my_purchases_default = defineTool4({
  name: "list_my_purchases",
  title: "List my Moontuner purchases",
  description: "List the signed-in user's Moontuner purchases: product type/label, amount, status, and fulfillment date.",
  inputSchema: {
    limit: z2.number().int().min(1).max(100).optional().describe("Maximum purchases to return. Default 25.")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser3(ctx).from("purchases").select("id, product_type, product_id, product_label, amount_cents, currency, status, fulfilled_at, created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 25);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { purchases: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "flrojnnbpankkrouthyz";
var mcp_default = defineMcp({
  name: "moontuner-mcp",
  title: "Moontuner",
  version: "0.1.0",
  instructions: "Moontuner tools. Read the current moon phase and, for the signed-in Moontuner user, their profile, natal harmonic reports, and purchase history.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    get_current_moon_phase_default,
    get_my_profile_default,
    list_my_natal_reports_default,
    list_my_purchases_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
